package FIrstVideoExercise;


/*
*
* Trying out multiple threads.
*
* I want to test out how multiple threads execute and behave if there are many of them
* that have been started.
*
* I know that they won't be executed in a particular pattern but I want to see it
* for myself.
*
* */
public class ExampleFive {

    public static void main(String[] args) {


        Runnable objectWithAction = () -> {

            Thread currentThread = Thread.currentThread();

            while( currentThread.isAlive() ){

                System.out.println("Thread is running : " + Thread.currentThread().getName() );
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
            }

        };

        for(int iterationCount = 0; iterationCount < 10; iterationCount++ ){

            Thread autoGeneratedTestThread = new Thread( objectWithAction, ("Thread number " + iterationCount) );
            autoGeneratedTestThread.start();
        }
    }

}
